# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "/tmp/main"
  cmd = "go build -o /tmp/main ."
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 300

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

