services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./database/migrations:/database/migrations
    command: [
      "-path", "/database/migrations",
      "-database", "${DATABASE_URL}",
      "up"
    ]

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=${GO_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
      - migrate

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  pgdata:
  caddy_data:
  caddy_config:

